name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Run hierarchy_json_to_csv.py
        run: python /scripts/hierarchy_json_to_csv.py

      - name: Show changes to hierarchy.csv (if any)
        run: |
          if [ -f public/hierarchy.csv ]; then
            echo "Changes in public/hierarchy.csv:"
            git diff --no-index public/hierarchy.csv.orig public/hierarchy.csv || true
          else
            echo "hierarchy.csv not found!"
          fi
        continue-on-error: true

      - name: Install, build, and upload your site
        uses: withastro/action@v3
        # with:
          # path: .
          # node-version: 20
          # package-manager: pnpm@latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
